### ISSUE TITLE
Is it possible to install ruby of lower version?

### ISSUE THREAD

**Issue by polarlights** [frol/docker-alpine-ruby#1]
If I run a alpine docker image and execute `apk add ruby`, it will install the latest ruby. I want to install specific version of ruby, ie. 1.8.7, 1.9.3, 2.2.2 etc. I execute `apk search ruby`, I can see only the latest ruby `2.2.4-r0`. Is it possible to install lower version package? Thank you very much.

**Comment by frol** [comment]
@polarlights I'm sorry, but it seems that there is no such feature in Alpine Linux, and since Alpine uses musl libc, you won't be able to use RVM unless they have ruby built against musl libc. It seems that you will need to compile the required version of Ruby yourself from sources. By the way, you can reuse Alpine APKBUILD of ruby package and it should make your life much easier since it will build a package for you, so you can even setup your own Alpine repo with various ruby versions.

**Comment by polarlights** [comment]
@frol  I see. I will try build my own package as the official website writes. Thanks a lot.
